name: My Target Workflow

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Permissions
        run: |
          chmod +x PullFeatures.sh

      - name: Execute Script
        run: |
          ./PullFeatures.sh
          
    
